application: gaestebin
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /components
  static_dir: components

- url: /partials
  static_dir: partials

- url: /api/.*
  script: _go_app

- url: /.*
  static_files: index.html
  upload: index\.html
  login: required
